name: Build

on:
  push:
    paths:
    - .github/workflows/build.yml
    - SiraUtil/**

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Set up Beat Saber
      uses: nicoco007/setup-beat-saber@v1
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        project-path: ${{ github.workspace }}\SiraUtil\SiraUtil.csproj

    - name: Add NuGet source
      run: dotnet nuget update source "nicoco007 GitHub Packages" --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text

    - name: Build Release
      id: build-release
      run: dotnet build ${{ github.workspace }}\SiraUtil\SiraUtil.csproj -c Release

    - name: Upload Release
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build-release.outputs.artifact-name }}
        path: ${{ steps.build-release.outputs.artifact-path }}
